### Create
POST http://localhost:8080/api/part/
Content-Type: application/json

{
  "partType": "Bremscheibe",
  "description": "Pirelli Vorderachse",
  "amountStored": "4"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.global.set("partType", response.body.partType);
client.global.set("description", response.body.description);
%}

### GetById
GET http://localhost:8080/api/part/partType={{partType}}&description={{description}}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### GetAll
GET http://localhost:8080/api/part/

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Update
PUT http://localhost:8080/api/part/partType={{partType}}&description={{description}}}
Content-Type: application/json

{
  "partType": "Bremscheibe",
  "description": "Pirelli Vorderachse",
  "amountStored": "4"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Delete
DELETE http://localhost:8080/api/part/partType={partType}&description={description}
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###