### Create
POST http://localhost:8080/api/reparation/
Content-Type: application/json

{
  "vehicleId": "1",
  "mechanicId": "1",
  "nextAppointment": "2022-01-17T07:00",
  "duration": "2"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.global.set("id", response.body.id);
%}

### GetById
GET http://localhost:8080/api/reparation/{{id}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### GetAll
GET http://localhost:8080/api/reparation/

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Update
PUT http://localhost:8080/api/reparation/{{id}}
Content-Type: application/json

{
  "vehicleId": "1",
  "mechanicId": "1",
  "nextAppointment": "2022-05-25T09:00",
  "duration": "2"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Delete
DELETE http://localhost:8080/api/reparation/{{id}}
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###